version: "3.9"

services:
  database:
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=gio
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ted_talks
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
volumes:
    pgdata:
